// doka_6.4.0/examples/svelte/src/DemoPreview.svelte
<script>
import { DokaOverlay, toURL } from './svelte-doka';

let enabled = false;
let imagePreviewCrop = {
    aspectRatio: .5,
    rotation: -1.5707963268
};
let imagePreviewSource = 'assets/photo-preview.jpeg';
let imageSource = 'assets/photo.jpeg';

const handleConfirm = (output) => {
    console.log('Confirm edit!', output);
    enabled = false;
    imagePreviewSource = toURL(output.file);
    imagePreviewCrop = output.data.crop;
}

const handleCancel = () => {
    console.log('Cancel edit!');
    enabled = false;
}

</script>

<div>

    <h2>Demo Preview</h2>

    <button on:click={() => enabled = true}>Show Overlay</button>

    <DokaOverlay
        {enabled}
        utils="crop"
        src={imageSource}
        crop={imagePreviewCrop}
        onconfirm={handleConfirm}
        oncancel={handleCancel}>
        <img src={imagePreviewSource} alt="">
    </DokaOverlay>
    
</div>

// doka_6.4.0/examples/vue/src/DemoPreview.vue
<template>
  <div id="demo-preview">

    <h2>Doka Preview</h2>

    <button @click="enabled=true">Show Overlay</button>

    <DokaOverlay 
      utils="crop"
      :enabled="enabled"
      :src="imageSource" 
      :crop="imagePreviewCrop"
      @confirm="handleDokaConfirm"
      @cancel="handleDokaCancel">
      <img :src="imagePreviewSource" alt="">
    </DokaOverlay>
    
  </div>
</template>

<script>
/* eslint-disable */
import { DokaOverlay, toURL } from './vue-doka';

export default {
  name: 'demo-overlay',
  components: { DokaOverlay },
  data () {
    return {
      enabled: false,
      imagePreviewCrop: {
        aspectRatio: .5,
        rotation: -1.5707963268
      },
      imagePreviewSource: 'assets/photo-preview.jpeg',
      imageSource: 'assets/photo.jpeg'
    }
  },
  methods: {
    handleDokaConfirm(output) {
      console.log('Confirm crop!', output);
      this.enabled = false;
      this.imagePreviewSource = toURL(output.file);
      this.imagePreviewCrop = output.data.crop;
    },
    handleDokaCancel() {
      console.log('Cancel crop!');
      this.enabled = false;
    }
  }
}
</script>
