// doka_6.4.0/examples/svelte/src/DemoInline.svelte
<script>
import { Doka } from './svelte-doka';

let cropAspectRatio = 1;

const handleConfirm = (output) => {
    console.log('Confirm edit!', output);
}

const handleCancel = () => {
    console.log('Cancel edit!');
}
</script>

<div>

    <h2>Demo Inline</h2>

    <Doka 
        style="width: 800px; height: 480px"
        src={'./assets/photo.jpeg'}
        utils='crop, filter, color, markup, resize'
        {cropAspectRatio}
        oncancel={handleCancel}
        onconfirm={handleConfirm}
        cropAspectRatioOptions={[
            {
                label: 'Free',
                value: null
            },
            {
                label: 'Portrait',
                value: 1.5
            },
            {
                label: 'Square',
                value: 1
            },
            {
                label: 'Landscape',
                value: .75
            }
        ]}/>
    
</div>

// doka_6.4.0/examples/vue/src/DemoInline.vue
<template>
  <div id="demo-inline">

    <h2>Doka Inline</h2>
    
    <Doka 
      ref="doka"
      style="height:400px"
      crop-aspect-ratio="1"
      utils="crop,filter,color,markup,resize"
      :crop-aspect-ratio-options="cropOptions"
      :src="src"
      @confirm="handleDokaConfirm"
      @cancel="handleDokaCancel"/>
      
  </div>
</template>

<script>
/* eslint-disable */
import { Doka } from './vue-doka/';

export default {
  name: 'demo-modal',
  components: { Doka },
  data () {
    return {
      src: 'assets/photo.jpeg',
      cropOptions: [
        {
          label: 'Free',
          value: null
        },
        {
          label: 'Portrait',
          value: 1.5
        },
        {
          label: 'Square',
          value: 1
        },
        {
          label: 'Landscape',
          value: .75
        }
      ]
    }
  },
  methods: {
    handleDokaConfirm(output) {
      console.log('Confirm crop!', output);
    },
    handleDokaCancel() {
      console.log('Cancel crop!');
    }
  }
}
</script>
