// doka_6.4.0/examples/vue/src/App.vue
<template>
  <div id="app">
    <h1>Doka Demos</h1>
    <DemoFilePond/>
    <DemoProfile/>
    <DemoModal/>
    <DemoInline/>
    <DemoPreview/>
  </div>
</template>

<script>
import DemoFilePond from './DemoFilePond.vue';
import DemoModal from './DemoModal.vue';
import DemoPreview from './DemoPreview.vue';
import DemoInline from './DemoInline.vue';
import DemoProfile from './DemoProfile.vue';

export default {
  name: 'app',
  components: { DemoFilePond, DemoModal, DemoInline, DemoPreview, DemoProfile }
}
</script>

<style>
#app {
  font-family: 'Avenir', Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  text-align: center;
  color: #2c3e50;
}
</style>

// doka_6.4.0/examples/svelte/src/App.svelte
<script>
import DemoInline from './DemoInline.svelte';
import DemoModal from './DemoModal.svelte';
import DemoPreview from './DemoPreview.svelte';
import DemoProfile from './DemoProfile.svelte';
</script>

<div>
	<h1>Doka Demos</h1>
	<DemoInline/>
	<DemoModal/>
	<DemoProfile/>
	<DemoPreview/>
</div>

<style>
div {
	margin: 0;
	padding:40px;
	font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", "Roboto", "Oxygen",
		"Ubuntu", "Cantarell", "Fira Sans", "Droid Sans", "Helvetica Neue",
		sans-serif;
	-webkit-font-smoothing: antialiased;
	-moz-osx-font-smoothing: grayscale;
}
</style>
