// doka_6.4.0/examples/vue/src/DemoModal.vue
<template>
  <div id="demo-modal">

    <h2>Doka Modal</h2>

    <button @click="enabled=true">Show Modal</button>

    <DokaModal 
      crop-aspect-ratio="1"
      :src="src" 
      v-if="enabled"
      @confirm="handleDokaConfirm"
      @cancel="handleDokaCancel"
      @close="enabled=false"/>
    
    <img v-if="result" :src="result" alt="" />
    
  </div>
</template>

<script>
/* eslint-disable */
import { DokaModal, toURL } from './vue-doka/';

export default {
  name: 'demo-modal',
  components: { DokaModal },
  data () {
    return {
      enabled: false,
      src: 'assets/photo.jpeg',
      result: null
    }
  },
  methods: {
    handleDokaConfirm(output) {
      console.log('Confirm crop!', output);
      this.result = toURL(output.file);
    },
    handleDokaCancel() {
      console.log('Cancel crop!');
    }
  }
}
</script>

// doka_6.4.0/examples/svelte/src/DemoModal.svelte
<script>
import { DokaModal, toURL } from './svelte-doka';

let src = 'assets/photo.jpeg';
let enabled = false;
let result = null;

const handleConfirm = (output) => {
    console.log('Confirm edit!', output);
    result = toURL(output.file);
}

const handleCancel = () => {
    console.log('Cancel edit!');
}

const handleClose = () => {
    console.log('Close edit!');
    enabled = false;
}
</script>

<div>

    <h2>Demo Modal</h2>

    <button on:click={() => enabled = true}>Show Modal</button>

    {#if enabled}
    <DokaModal
        {src}
        cropAspectRatio="1"
        onconfirm={handleConfirm}
        oncancel={handleCancel}
        onclose={handleClose}/>
    {/if}
    
    {#if result}
    <img src={result} alt="" />
    {/if}
    
</div>
